### ISSUE TITLE
Add root parameter to employee

### ISSUE THREAD

**Issue by p-carrier** [Chrysalis-Papilio/Soen490-Papilio-Website#3]
During the business creation, an employee is created as the root account of the business. The root parameter is not yet available in the backend so I am creating an issue to keep track of this.

This is what it should look like in the login file at the end: 
```
employee: {
    firstName: data.adminAccount.adminName.split(' ')[0],
    lastName: data.adminAccount.adminName.split(' ')[1],
    email: data.adminAccount.adminEmail,
    firebase_id: user.uid,
    role: data.adminAccount.role,
    root: true,  // this will need to be added
},
```

**Comment by mth-1012** [comment]
it's there now 👋

**Comment by p-carrier** [comment]
Perfect it has been added to PR #2
